import type { ReactNode } from 'react';
import { BookOpen, Building2, ChevronLeft, ChevronRight, CircleEllipsis, Clock3, FileText, GraduationCap, Home, Search, Star, UserRound, X } from 'lucide-react';
import { Link, NavLink } from 'react-router-dom';
import type { CatalogDocument } from '@rpd/shared';

export function MobileHeader() { return <header className="mobile-header" role="banner"><span className="header-cancel">Отмена</span><Link className="header-brand" to="/"><strong>РПД</strong><small>мини-приложение</small></Link><button className="header-more" type="button" aria-label="Дополнительные действия"><CircleEllipsis size={20} /></button></header>; }
export function BottomNavigation() { const items = [{ to: '/', label: 'Главная', icon: Home }, { to: '/favorites', label: 'Избранное', icon: Star }, { to: '/profile', label: 'Профиль', icon: UserRound }]; return <nav className="bottom-nav" aria-label="Основная навигация">{items.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} className="nav-item tap">{({ isActive }) => <><Icon size={21} fill={isActive ? 'currentColor' : 'none'} aria-hidden="true" /><span>{label}</span></>}</NavLink>)}</nav>; }
export function ScreenHeading({ title, subtitle, back }: { title: string; subtitle?: string; back?: string }) { return <><div className="screen-heading">{back && <Link to={back} className="back-link tap" aria-label="Назад"><ChevronLeft size={25} /></Link>}<h1>{title}</h1></div>{subtitle && <p className="screen-subtitle">{subtitle}</p>}</>; }
export function SearchField({ id, value, onChange, placeholder }: { id: string; value: string; onChange(value: string): void; placeholder: string }) { return <label className="search-field" htmlFor={id}><Search size={17} aria-hidden="true" /><span className="sr-only">{placeholder}</span><input id={id} type="search" value={value} onChange={(event) => onChange(event.currentTarget.value)} placeholder={placeholder} />{value && <button type="button" className="clear-search" onClick={() => onChange('')} aria-label="Очистить поиск"><X size={16} /></button>}</label>; }
export function EducationCard({ to, kind, title, detail }: { to: string; kind: 'bachelor' | 'master'; title: string; detail: string }) { return <Link className="ui-card education-card tap" to={to}><span className={`education-icon ${kind === 'master' ? 'master' : ''}`}>{kind === 'bachelor' ? <GraduationCap size={29} /> : <BookOpen size={27} />}</span><span className="card-copy"><strong>{title}</strong><small>{detail}</small></span><ChevronRight className="chevron" size={20} /></Link>; }
export function CourseCard({ to, course }: { to: string; course: number }) { return <Link className="ui-card course-card tap" to={to}><Building2 className="icon" size={24} /><strong>{course} курс</strong><ChevronRight className="chevron" size={18} /></Link>; }
export function DocumentRow({ document, state, recent = false }: { document: CatalogDocument; state?: object; recent?: boolean }) { return <Link className="ui-card document-row tap" to={`/document/${document.id}`} state={state}><span className="document-icon"><FileText size={19} /></span><span className="document-copy"><strong>{document.name}</strong>{document.code && <small>{document.code}</small>}</span>{recent ? <Clock3 size={19} color="var(--brand)" /> : <ChevronRight className="chevron" size={17} />}</Link>; }
export function ProgramCard({ title, children }: { title: string; children: ReactNode }) { return <article className="ui-card program-card"><Building2 className="icon" size={27} /><div><h2>{title}</h2><div className="course-pills">{children}</div></div><ChevronRight className="chevron" size={17} /></article>; }
export function CoursePill({ to, children }: { to: string; children: ReactNode }) { return <Link className="course-pill tap" to={to}>{children}</Link>; }
export function InlineNotice({ kind, children }: { kind?: 'success' | 'error'; children: ReactNode }) { return <div className={`inline-notice ${kind ?? ''}`} role={kind === 'error' ? 'alert' : 'status'}>{children}</div>; }
